package br.ufsc.ppgcc.experion.view.profile;

import br.ufsc.ppgcc.experion.model.expert.Expert;
import br.ufsc.ppgcc.experion.view.expertise.Expertise;
import br.ufsc.ppgcc.experion.view.profile.builder.ProfileBuilder;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * A profile is generated by analyzing a set of expertise associated to an expert and generating a more concise representation
 * of them.
 *
 * @author Rodrigo Gonçalves
 * @version 2019-03-05 - First version
 *
 */
@Entity
public class Profile implements Serializable {

    /** Primary key - auto-generated by JPA */
    @GeneratedValue
    @Id
    private int id;

    /** Profile description */
    @Lob
    private String description;

    /** The expert associated with this expertise */
    @ManyToOne
    private Expert expert;

    /** The expertise used to generate this profile **/
    @ManyToMany
    private Set<Expertise> expertise = new HashSet<>();

    /** The ProfileBuilder used to generate this profile */
    @ManyToOne
    private ProfileBuilder builder;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Expert getExpert() {
        return expert;
    }

    public void setExpert(Expert expert) {
        this.expert = expert;
    }

    public Set<Expertise> getExpertise() {
        return expertise;
    }

    public void setExpertise(Set<Expertise> expertise) {
        this.expertise = expertise;
    }

    public ProfileBuilder getBuilder() {
        return builder;
    }

    public void setBuilder(ProfileBuilder builder) {
        this.builder = builder;
    }
}
