package br.ufsc.ppgcc.experion.extractor.evidence;

import br.ufsc.ppgcc.experion.extractor.input.EvidenceSourceInput;
import br.ufsc.ppgcc.experion.extractor.source.EvidenceSourceURL;
import br.ufsc.ppgcc.experion.model.expert.Expert;
import org.apache.commons.lang3.StringUtils;

import javax.persistence.*;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * A physical evidence is an expertise evidence, collected from a EvidenceDataSource by
 * an EvidenceSourceInput.
 *
 * @author Rodrigo Gonçalves
 * @version 2019-03-05 - First version
 *
 */
@Entity
public class PhysicalEvidence implements Serializable {

    /** Primary key - auto-generated by JPA */
    @Id
    @GeneratedValue
    private int id;

    /** Set of keywords associated with the evidence */
    @ElementCollection
    private Set<String> keywords = new HashSet<String>();

    /** Expert associated to this evidence */
    @ManyToOne(fetch = FetchType.EAGER)
    private Expert expert;

    /** Timestamp associated to this evidence */
    private Date timestamp;

    /** An evidence source object, which explains how to retrieve the document from which the evidence was generated */
    @OneToOne(cascade = CascadeType.ALL)
    private EvidenceSourceURL url;

    /** The language (ISO language code) of the document which originated the evidence */
    private String language;

    /** The input responsible for generating this evidence */
    @ManyToOne(fetch = FetchType.EAGER)
    private EvidenceSourceInput input;

    /** When this evidence was collected/created */
    private Date collectedDateTime;

    private static String dumpFormat = "(%s)=> %s";

    public String toString() {
        return dumpFormat.format(dumpFormat, SimpleDateFormat.getDateTimeInstance().format(timestamp), StringUtils.join(keywords, ", "));
    }

    public PhysicalEvidence() {

    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public Set<String> getKeywords() {
        return keywords;
    }

    public void setKeywords(Set<String> keywords) {
        this.keywords = keywords;
    }

    public Expert getExpert() {
        return expert;
    }

    public void setExpert(Expert expert) {
        this.expert = expert;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public EvidenceSourceURL getUrl() {
        return url;
    }

    public void setUrl(EvidenceSourceURL url) {
        this.url = url;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public EvidenceSourceInput getInput() {
        return input;
    }

    public void setInput(EvidenceSourceInput input) {
        this.input = input;
    }

    public Date getCollectedDateTime() {
        return collectedDateTime;
    }

    public void setCollectedDateTime(Date collectedDateTime) {
        this.collectedDateTime = collectedDateTime;
    }

    /** Helper method to add keywords to this physical evidence */
    public void addKeywords(String[] keywords) {
        for (String keyword : keywords) {
            this.getKeywords().add(keyword);
        }
    }
}
