package br.ufsc.ppgcc.experion.extractor.source;

import javax.persistence.*;
import java.io.Serializable;

/**
 * A very generic class, which basically defines that an EvidenceSourceURL must contain an URL
 *
 * @author Rodrigo Gonçalves
 * @version 2019-03-05 - First bersion
 *
 * */
@Entity
public class EvidenceSourceURL implements Serializable {

    /** Primary key - auto-generated by JPA */
    @Id
    @GeneratedValue
    private Integer id;

    /** URL for this evidence source */
    @Lob
    private String url;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * If possible, should provide the retrieved data directly, without using the URL
     * @return
     */
    @Lob
    private String retrievedData;

    public String getRetrievedData() {
        return retrievedData;
    }

    public void setRetrievedData(String retrievedData) {
        this.retrievedData = retrievedData;
    }
}
