package br.ufsc.ppgcc.experion.extractor.source;

import br.ufsc.ppgcc.experion.extractor.input.EvidenceSourceInput;
import br.ufsc.ppgcc.experion.extractor.input.engine.EvidenceSourceInputEngine;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * An evidence source is any data source from which expertise evidence can be extracted. Over an input several extractions
 * (EvidenceSourceInput) can be applied, varying the method and parameters used.
 *
 * @author Rodrigo Gonçalves
 * @version 2019-03-05 - First version
 *
 */
@Entity
public class EvidenceSource implements Serializable {

    /** Primary key - auto-generated by JPA */
    @Id
    @GeneratedValue
    private Integer id;

    /** Identifier (name) for this evidence source */
    @Column(unique = true)
    private String name;

    /** URl for the source, if available */
    private String url;

    /** Aditional comments about the source **/
    private String comments;

    /** Which extractors are configured for this evidence source */
    @OneToMany(mappedBy = "source", cascade = CascadeType.ALL)
    @JsonManagedReference
    private Set<EvidenceSourceInput> inputs = new HashSet<>();

    public EvidenceSource(String name, String url) {
        this.name = name;
        this.url = url;
    }

    public EvidenceSource(String name) {
        this.name = name;
    }

    public EvidenceSource() {
    }

    /** Helper method to create a new EvidenceSourceInput for a given engine class */
    public EvidenceSourceInput addInputEngine(EvidenceSourceInputEngine engine) {
        EvidenceSourceInput input = new EvidenceSourceInput();
        input.setName(this.name + "-" + engine.getClass().getSimpleName());
        input.setEngineClassName(engine.getClass().getCanonicalName());
        input.setEngine(engine);
        inputs.add(input);
        return input;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getComments() {
        return comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public Set<EvidenceSourceInput> getInputs() {
        return inputs;
    }

    public void setInputs(Set<EvidenceSourceInput> inputs) {
        this.inputs = inputs;
    }

    @Override
    public String toString() {
        return "EvidenceSource{" +
                "name='" + name + '\'' +
                ", url='" + url + '\'' +
                '}';
    }
}
