package br.ufsc.ppgcc.experion.view.expertise;

import br.ufsc.ppgcc.experion.model.evidence.LogicalEvidence;
import br.ufsc.ppgcc.experion.model.expert.Expert;
import br.ufsc.ppgcc.experion.view.expertise.builder.ExpertiseBuilder;

import javax.persistence.*;
import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * An expertise associated to a given expert, generated by analyzing a set of LogicalEvidence.
 *
 * @author Rodrigo Gonçalves
 * @version 2019-05-03 - First version
 *
 */
@Entity
public class Expertise implements Serializable {

    /** Primary key - auto-generated by JPA */
    @GeneratedValue
    @Id
    private int id;

    /** Expertise description */
    @Lob
    private String description;

    /* The logical evidences used to generate the expertise */
    @ManyToMany(fetch = FetchType.EAGER)
    private Set<LogicalEvidence> evidences = new HashSet<>();

    /* The expert associated with this expertise */
    @ManyToOne
    private Expert expert;

    /* The ExpertiseBuilder used to generate this expertise */
    @ManyToOne
    private ExpertiseBuilder builder;

    /* The language from the evidences where this expertise was generated */
    private String language;

    public String toString() {
        return this.getDescription();
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Set<LogicalEvidence> getEvidences() {
        return evidences;
    }

    public void setEvidences(Set<LogicalEvidence> evidences) {
        this.evidences = evidences;
    }

    public Expert getExpert() {
        return expert;
    }

    public void setExpert(Expert expert) {
        this.expert = expert;
    }

    public ExpertiseBuilder getBuilder() {
        return builder;
    }

    public void setBuilder(ExpertiseBuilder builder) {
        this.builder = builder;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }
}
