package br.ufsc.ppgcc.experion.model.expert;

import br.ufsc.ppgcc.experion.extractor.source.EvidenceSource;
import com.fasterxml.jackson.annotation.JsonBackReference;

import javax.persistence.*;
import java.io.Serializable;

/**
 * Represents an expert identification in a given source
 *
 * @author Rodrigo Gonçalves
 * @version 2019-03-05 - First version
 *
 */
@Entity
public class ExpertSourceIdentification implements Serializable {

    /** Primary key - auto-generated by JPA */
    @GeneratedValue
    @Id
    private int id;

    /** For which source this identification is applicable */
    @ManyToOne(fetch = FetchType.EAGER)
    private EvidenceSource source;

    /** The expert associated with this identification */
    @ManyToOne
    @JsonBackReference
    private Expert expert;

    /** The expert's identification for the EvidenceSource */
    private String identification;

    public ExpertSourceIdentification(Expert expert, EvidenceSource source, String identification) {
        this.source = source;
        this.expert = expert;
        this.identification = identification;
    }

    public ExpertSourceIdentification() {
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public EvidenceSource getSource() {
        return source;
    }

    public void setSource(EvidenceSource source) {
        this.source = source;
    }

    public Expert getExpert() {
        return expert;
    }

    public void setExpert(Expert expert) {
        this.expert = expert;
    }

    public String getIdentification() {
        return identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }
}
