package br.ufsc.ppgcc.experion.model.expert;

import br.ufsc.ppgcc.experion.extractor.source.EvidenceSource;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import javax.persistence.*;
import java.io.Serializable;
import java.util.*;

/**
 * Represents an expert
 *
 * @author Rodrigo Gonçalves
 * @version 2019-03-5 - First version
 *
 */
@Entity
public class Expert implements Serializable {

    /** Primary key - auto-generated by JPA */
    @GeneratedValue
    @Id
    private int id;

    /** Global identification for the expert - independent of a given source - passport, etc. */
    private String identification;

    /** The expert full name */
    private String name;

    /** The expert date of birth */
    private Date dateOfBirth;

    /** How this expert is identified in the existing EvidenceSource. An expert may have more than one identification per EvidenceSource */
    @OneToMany(mappedBy = "expert", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @JsonManagedReference
    private Set<ExpertSourceIdentification> identifications = new HashSet<>();

    public Expert(String identification, String name, Date dateOfBirth) {
        this.identification = identification;
        this.name = name;
        this.dateOfBirth = dateOfBirth;
    }

    public Expert(String identification, String name) {
        this.identification = identification;
        this.name = name;
    }

    public Expert() {

    }

    /** Helper method to quickly retrieve an expert identification for a given source. If no specific identification is found,
     * return the global identification for the expert. */
    public String getIdentificationForSource(EvidenceSource source) {
        Optional<ExpertSourceIdentification> ident = identifications.stream().filter(id -> id.getSource().equals(source)).findFirst();
        if (ident.isPresent()) {
            return ident.get().getIdentification();
        } else {
            return this.identification;
        }
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getIdentification() {
        return identification;
    }

    public void setIdentification(String identification) {
        this.identification = identification;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getDateOfBirth() {
        return dateOfBirth;
    }

    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    public Set<ExpertSourceIdentification> getIdentifications() {
        return identifications;
    }

    public void setIdentifications(Set<ExpertSourceIdentification> identifications) {
        this.identifications = identifications;
    }
}
